name: Azure Pipelines
variables:
  python.version: '3.7.6'
  webAppName: 'QualityRelease-AppService'
  azureServiceConnectionId: '76b1e36a-6202-4055-914a-1618f6c3575e'


stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    # Needed for Terraform VM deployment
    # - task: InstallSSHKey@0
    #   inputs:
    #      knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
    #     '
    #     sshKeySecureFile: '../id_rsa.pub'
 
     - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
       displayName: 'Use Terraform latest'
       inputs: 
          terraformVersion: '0.13.2'
     
     - task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
       displayName: Terraform Initialize
       inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: './terraform'
          backendServiceArm: 'QRServiceConnection'
          backendAzureRmResourceGroupName: 'MyResGroup'
          backendAzureRmStorageAccountName: 'udaqualityrelease'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'prod.terraform.tfstate'  
          allowTelemetryCollection: true
          
     
     - task:  charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
       displayName: Terraform plan
       inputs:
          command: 'plan'
          workingDirectory: './terraform'
      
     - task:  charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
       displayName: Terraform Apply
       inputs:
          command: 'apply'
          workingDirectory: './terraform'
          backendType: azurerm
          allowTelemetryCollection: true

 
